version: '3'            # version of the docker compose (?)
services:               # indicates the services/containers block
  web:                  # service name
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:              # ports to be mapped
      - "3000:3000"
    volumes:
      - /home/node/app/node_modules
      - .:/home/node/app
  tests:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /home/node/app/node_modules
      - .:/home/node/app
    command: ["npm", "run", "test"]
